name: Code Quality and Coverage

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Change if you're using a different version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py')

  coverage:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=term-missing

      - name: Upload coverage to GitHub summary
        run: |
          echo '### Test Coverage Summary' >> $GITHUB_STEP_SUMMARY
          pytest --cov=. --cov-report=term | tee /tmp/coverage.txt
          tail -n 20 /tmp/coverage.txt >> $GITHUB_STEP_SUMMARY
